TrainingPage-API-Integration
mishelshaji/EXP-G3-IDP pull request #14
Opened 2023-02-18 06:33 UTC by athulmuraleedharan

2023-02-18 06:46 UTC, mishelshaji requested changes

2023-02-18 06:46 UTC, mishelshaji commented on client/idp/src/Types/Dto/training.dto.d.ts
> +     Name : string,
Format the code.

2023-02-18 06:46 UTC, mishelshaji commented on client/idp/src/Types/Dto/training.dto.d.ts
> +declare interface TrainingViewDto{
Check naming convention.

2023-02-18 07:06 UTC, athulmuraleedharan commented on client/idp/src/Types/Dto/training.dto.d.ts
> +     Name : string,
corrected

2023-02-18 07:07 UTC, athulmuraleedharan commented on client/idp/src/Types/Dto/training.dto.d.ts
> +declare interface TrainingViewDto{
corrected

2023-02-19 07:13 UTC, mishelshaji commented on client/idp/src/app/shared/objective-detailed/objective-detailed.component.html
> +                        <td>{{training.Id}}</td>
use camelCasing for property values.

2023-02-19 07:16 UTC, mishelshaji approved these changes

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/shared/objective-detailed/objective-detailed.component.html
> +                        <td>{{training.Name}}</td>
use camelCasing for property values.

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/shared/objective-detailed/objective-detailed.component.html
> +                        <td>{{training.Link}}</td>
use camelCasing for property values.

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/shared/objective-detailed/objective-detailed.component.html
> +                        <td>{{training.Progress}}</td>
use camelCasing for property values.

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/shared/objective-detailed/objective-detailed.component.html
> +                        <td>{{training.StartDate}}</td>
use camelCasing for property values.

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/shared/objective-detailed/objective-detailed.component.html
> +                        <td>{{training.EndDate}}</td>
use camelCasing for property values.

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/shared/objective-detailed/objective-detailed.component.html
> +                        <td>{{training.UserId}}</td>
use camelCasing for property values.

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/shared/objective-detailed/objective-detailed.component.html
> +                        <td>{{training.IdpId}}</td>
use camelCasing for property values.

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/shared/objective-detailed/objective-detailed.component.html
> +                        <td>{{training.ObjectiveId}}</td>
use camelCasing for property values.

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/shared/objective-detailed/objective-detailed.component.ts
>    edit: boolean = false;
Remove the type specification. Also, add a blank line above.

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/user/user-routing.module.ts
> +      { path: 'objective', component: CreateObjectiveComponent },
Remove the trailing comma.

2023-02-19 07:16 UTC, mishelshaji commented on client/idp/src/app/user/user-routing.module.ts
> +  exports: [RouterModule],
Remove the trailing comma.

2023-02-19 10:00 UTC, merged